addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.8.4")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox" % "0.10.7")
addSbtPlugin("com.github.sbt" % "sbt-site-paradox" % "1.7.0")
addSbtPlugin("com.github.sbt" % "sbt-ghpages" % "0.9.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.20.1")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.17")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.8.1")
